version: '3'
services:
  db:
    image: mdillon/postgis:10
    restart: always
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: johnpassword
      POSTGRES_DB: john
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes:
      - ./frontend:/usr/local/src/john/
  app:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - "db"
    environment:
      FLASK_PORT: 5000
      FLASK_APP: /usr/local/john/main.py
    volumes:
      - ./python:/usr/local/john
